### ISSUE TITLE
crate name with dash

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [mcorbin/meuse#35] opened 2021-01-09 15:30 UTC
I have tried to publish on my private crate the `gloo-file` dependency.
It works but not when I try to depend on it in an another project.

Do you think it can be a Meuse issue ?

**Comment by mcorbin** [comment] 2021-01-09 15:33
>  It works but not when I try to depend on it in an another project.

What is the error returned to Cargo ? Do you see any error log in Meuse ?

**Comment by MarcAntoine-Arnaud** [comment] 2021-01-09 15:36
I have tried to push it with `gloo_file` but I get again:
```
error: no matching package named `gloo_file` found
```

**Comment by mcorbin** [comment] 2021-01-09 21:31
I will make some tests to see if I can reproduce.

**Comment by mcorbin** [comment] 2021-01-09 21:46
I'm unable to reproduce the issue.

i've pushed a crate named `test_1` on Meuse and use it as a dependency in another project, and it works as expected:

Here are Meuse logs:

```
INFO [2021-01-09 22:42:13,554] qtp1758192858-22 - meuse.api.crate.new publishing crate test_1 version 0.2.3
DEBUG [2021-01-09 22:42:13,579] qtp1758192858-22 - meuse.git git command add .
DEBUG [2021-01-09 22:42:13,590] qtp1758192858-22 - meuse.git git command status code= 0 out=  err= 
DEBUG [2021-01-09 22:42:13,591] qtp1758192858-22 - meuse.git git command commit -m test_1 0.2.3 -m meuse published test_1 0.2.3
DEBUG [2021-01-09 22:42:13,688] qtp1758192858-22 - meuse.git git command status code= 0 out= [master b3f8035] test_1 0.2.3
 2 files changed, 35 insertions(+)
 create mode 100644 te/st/test_1
 err= 
DEBUG [2021-01-09 22:42:13,689] qtp1758192858-22 - meuse.git git command push origin master
DEBUG [2021-01-09 22:42:17,703] qtp1758192858-22 - meuse.git git command status code= 0 out=  err= To github.com:mcorbin/testregistry.git
   fe34831..b3f8035  master -> master
DEBUG [2021-01-09 22:43:36,050] qtp1758192858-20 - meuse.interceptor.route request 85809a94-1416-4e8f-ab97-4f48a577f7bb uri /api/v1/crates/test_1/0.2.3/download method :get
INFO [2021-01-09 22:43:36,052] qtp1758192858-20 - meuse.api.crate.download serving crate file for crate test_1 version 0.2.3
```
We can see that the crate is correctly published and then downloaded.

Are you using the latest Meuse release ?

**Comment by MarcAntoine-Arnaud** [comment] 2021-01-10 15:26
Yes it's publish.
It's when I try to use it from an another project as a dependency.

Thank for your help !

**Comment by mcorbin** [comment] 2021-01-10 15:39
>  It's when I try to use it from an another project as a dependency.

It's what I did in my test, and the crate was correctly downloaded.
Can you send me the Meuse logs when you try to download the crate ?

**Comment by mcorbin** [comment] 2021-01-17 16:53
Hello,

Do you still have the issue ?

**Comment by mcorbin** [comment] 2021-02-09 21:51
I'l closing this issue, feel free to reopen if you still have the problem.

**Closed as completed** 2021-02-10 12:12 UTC
